# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170310_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.CharField(choices=[('R1', 'Rails'), ('R2', 'Ruby'), ('H', 'HTML'), ('J', 'JS'), ('P', 'PY'), ('O', 'Other')], default='R1', max_length=1),
            preserve_default=False,
        ),
    ]
