# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='guest', max_length=20),
            preserve_default=False,
        ),
    ]
