# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(to='board.Tag'),
        ),
    ]
