# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_post_tag_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='board.Tag'),
        ),
    ]
