# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_post_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
