# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:57
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20170330_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='board/post/%Y/%m/%d'),
        ),
    ]
